version: "3.7"

services:
    uniown-backend:
        build: .
        image: "uniown-backend:latest"
        container_name: uniown-backend
        ports:
            - "5005:5005"
        restart: unless-stopped
        init: true
        env_file:
            - .env.development.local
        networks:
            uniown-backend:

    mongodb:
        image: mongo:latest
        container_name: mongodb
        ports:
            - "27037-27039:27017-27019"
        restart: unless-stopped
        env_file:
            - .env.development.local
        init: true
        volumes:
            - mongodb-data:/data/db
        networks:
            uniown-backend:
                aliases:
                    - mongo.internal.uniown-backend.org

    redis_uniown_backend:
        image: redis:latest
        container_name: redis_uniown_backend
        ports:
            - "6390:6379"
        restart: unless-stopped
        init: true
        networks:
            uniown-backend:
                aliases:
                    - redis.internal.uniown-backend.org

networks:
    uniown-backend:
        name: uniown-backend-network
        driver: bridge

volumes:
    mongodb-data:
